# Generated by Django 4.1.3 on 2022-11-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("My_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="customer_phone", unique_together=set(),),
        migrations.AlterUniqueTogether(name="owner_phone", unique_together=set(),),
    ]
